import { Geist, Geist_Mono, Playwrite_GB_J } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playwrite = Playwrite_GB_J({
  subsets: ["latin"],
   variable: "--font-playwrite",
  weight: ["100", "200", "300", "400"], // Optional: specify weights (Thin to Regular)
  style: ["normal", "italic"], // Optional: include italic variant if needed
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${playwrite.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
